version: '3.8'

services:
  mysql_docker:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql_docker
      PMA_PORT: 3306
    ports:
      - "8080:80"
